spring:
  # datasource
  datasource:
    url: jdbc:mysql://134.175.146.243:33061/mall_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhou_huan_1997

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: cn.iocoder.mall.user.biz.dataobject

# dubbo
dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://121.43.168.82:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: cn.iocoder.mall.user.biz.service
  provider:
    filter: -exception
    MobileCodeService:
      version: 1.0.0
    UserAccessLogService:
      version: 1.0.0
    UserAddressService:
      version: 1.0.0
    UserService:
      version: 1.0.0
    UserProductSpuCollectionsService:
      version: 1.0.0
  consumer:
    OAuth2Service:
      version: 1.0.0

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: user-producer-spu-collection-group
